/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.anosym.teh.request.rms;

import com.anosym.teh.request.PostRequest;
import com.anosym.teh.response.ReportErrorResponse;
import com.anosym.teh.response.Response;
import java.math.BigDecimal;

/**
 *
 * @author marembo
 */
public class RMSFundTransferRequest extends PostRequest {

  /**
   * The token must be the one which is generated by External Token Check API. For ALL level don’t
   * pass the segment. Send segment=”COM” for commodity level only. For bringing in funds the
   * transtype of the request should be PAYIN. For taking out funds the transtype of the request
   * should be PAYOUT
   *
   * @param userId
   * @param token
   * @param accountId
   * @param amount
   * @param transactionType
   * @param segment
   */
  public RMSFundTransferRequest(String userId, String token, String accountId,
          BigDecimal amount, String transactionType, String segment) {
    super("/XMLServlets/servlet/FundTransfer", userId, token, accountId);
  }

  @Override
  protected Response getResponse(String response) {
    /**
     * The documentation must be misleading here. It says both the success and unsuccessful returns
     * response in the report error response.
     */
    return processResponse(response, ReportErrorResponse.class);
  }
}
