/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.anosym.teh.request.rms;

import com.anosym.teh.request.PostRequest;
import com.anosym.teh.response.ReportErrorResponse;
import com.anosym.teh.response.Response;
import java.math.BigDecimal;

/**
 *
 * @author marembo
 */
public class RMSFundTransferEXERequest extends PostRequest {

  /**
   * Token should be same as the one which is generated by the NT(EXE). For bringing in funds the
   * transtype of the request should be PAYIN. For taking out funds the transtype of the request
   * should be PAYOUT.
   *
   * @param userId
   * @param token
   * @param accountId
   * @param amount
   * @param transactionType
   */
  public RMSFundTransferEXERequest(String userId, String token, String accountId,
          BigDecimal amount, String transactionType) {
    super("/XMLServlets/servlet/FundTransfer_EXE");
    addParameter("sLoginId", userId);
    addParameter("token", token);
    addParameter("acId", accountId);
    addParameter("amount", amount);
    addParameter("transtype", transactionType);
  }

  @Override
  protected Response getResponse(String response) {
    return processResponse(response, ReportErrorResponse.class);
  }
}
